name: Build AppImage

on:
  workflow_dispatch: # Allows you to run this manually with a button click

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt-get clean
        sudo apt-get update --fix-missing
        sudo apt-get install -y imagemagick file desktop-file-utils


    - name: Download pkg2appimage
      run: |
        wget -c https://github.com/AppImageCommunity/pkg2appimage/releases/download/continuous/pkg2appimage-1eceb30-x86_64.AppImage
        chmod +x pkg2appimage-1eceb30-x86_64.AppImage

    - name: Build AppImage
      run: |
        # Explicitly download the large deb file locally into the current workspace folder
        wget -c "https://github.com/brave/brave-browser/releases/download/v1.91.175/brave-browser_1.91.175_amd64.deb" -O brave.deb
        
        # Run the build tool pointing to our standardized local package
        ./pkg2appimage-1eceb30-x86_64.AppImage --appimage-extract-and-run recipe.yml

    - name: Upload Finished AppImage
      uses: actions/upload-artifact@v4
      with:
        name: Finished-AppImage
        path: out/*.AppImage
