name: Build AppImage

on:
  workflow_dispatch: # Allows you to run this manually with a button click

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt-get clean
        sudo apt-get update --fix-missing
        sudo apt-get install -y imagemagick file desktop-file-utils


    - name: Download pkg2appimage
      run: |
        wget -c https://github.com/AppImageCommunity/pkg2appimage/releases/download/continuous/pkg2appimage-1eceb30-x86_64.AppImage
        chmod +x pkg2appimage-1eceb30-x86_64.AppImage

    - name: Build AppImage
      run: |
        wget -c "https://github.com" -O brave.deb
        mkdir -p brave.AppDir/usr/bin
        mkdir -p brave.AppDir/usr/share/applications
        mkdir -p brave.AppDir/usr/share/icons/hicolor/128x128/apps
        dpkg-deb -x brave.deb brave.AppDir/
        cp -r brave.AppDir/opt/://brave.com* brave.AppDir/usr/bin/ || true
        cp brave.AppDir/opt/://brave.combrave-browser.desktop brave.AppDir/usr/share/applications/brave.desktop || true
        cp brave.AppDir/opt/://brave.comproduct_logo_128.png brave.AppDir/usr/share/icons/hicolor/128x128/apps/brave.png || true
        ./pkg2appimage-1eceb30-x86_64.AppImage --appimage-extract-and-run recipe.yml



    - name: Upload Finished AppImage
      uses: actions/upload-artifact@v4
      with:
        name: Finished-AppImage
        path: out/*.AppImage
